### ISSUE TITLE
Odd Looping FLAC Implementation

### ISSUE THREAD

**Issue by Danhanado** [emoose/OutRun2006Tweaks#86] opened 2024-07-23 12:10 UTC
### Describe the feature you'd like to see added

As it is now, if I set LoopStart and LoopEnd to the segment I want to loop, the music will only play the segment, so all the audio before the LoopStart point is skipped.

The way looping audio works with vgmstream is the audio will play from the beginning of the file, and then continuously loop back around to the LoopStart once it reaches the LoopEnd.

I think this would be best way to go about it as it would make it easy to convert existing looping audio and would make the LoopLength tag unnecessary.

**Comment by emoose** [comment] 2024-07-23 12:50
> the music will only play the segment, so all the audio before the LoopStart point is skipped.

Hm strange, it's meant to work like how you mentioned vgmstream does, maybe something got broken around it recently (there was a hang issue with FLACs a little while ago, maybe that fix broke part of this...)

Looking at the code I don't see anything too obvious for it though, the only time it should be seeking back to LoopStart is once current sample number is past LoopEnd.

Maybe it's not reading the LoopEnd sample number properly, does the log mention anything about the loop? Should have something like "FLAC loop: x - y" inside

**Comment by Tenome** [comment] 2024-07-23 22:03
I think it worked as intended last time I tried it (I gave up making looped edits for now, too time consuming and someone else is already doing the main soundtrack). Upload your FLAC, it'll be easier to troubleshoot that way.

**Comment by Danhanado** [comment] 2024-07-24 01:34
Alright ([Link](https://drive.google.com/file/d/1Y7IcnwyVWQQVyrJvD95-ZxK50lMbiAkG/view?usp=sharing))

**Comment by Tenome** [comment] 2024-07-24 04:15
Hmm. I just tried two of my own loops files ([link ](https://mega.nz/folder/FnMTDa4I#2EzLDLdCbP_O46HKJfXx7w)-- one I made and one random one from another game) and they seemed to work as intended. 

I think I found what the issue is. The loop tags aren't being cached when you first switch over to the song in the CD Player, but if you load the song, switch, and then switch back, it seems to play and loop as intended. I put two versions of Magic Shower in the folder with really obvious abrupt loops in the beginning for testing.

**Comment by Danhanado** [comment] 2024-07-24 09:42
I haven't used the cd switcher but same as mine, your music doesn't start at the beginning

**Comment by emoose** [comment] 2024-07-24 10:31
Ah might have found the cause, the current sample number wasn't being inited to 0 in release builds, probably used some random large number as the sample num, so the loop code would think it went past loop end and put it back to the loop start.
(debug builds would have always inited to 0 iirc, so probably why it worked fine when I first tested it, thanks for letting me know)

Should hopefully be fixed in latest action build: https://github.com/emoose/OutRun2006Tweaks/actions/runs/10074968021

**Closed** 2024-08-13 22:22 UTC
