### ISSUE TITLE
Unstretch C2C's user interface to the original arcade 4:3 aspect ratio

### ISSUE THREAD

**Issue by Wiinansa** [emoose/OutRun2006Tweaks#18] opened 2024-06-24 00:27 UTC
Hello, one issue of the UI in Outrun 2006 C2C is that the UI is stretched to 16:9 aspect ratio from a 4:3 base.

I'm providing a comparison link on imgsli, it can give you an idea of the issue at hand, the dropdown also allows you to check the issue in menus as well: https://imgsli.com/Mjc0MTI0/0/1

I don't know if you're aware of Teknoparrot, the arcade emulator, but running the arcade game (which runs on windows direct9 i'm pretty sure) with the Jennifer_VGA.exe (the base Jennifer.exe also stretches) showcases the game user interface in proper 4:3 unstretched aspect ratio (alongside much higher quality assets that I wish I could dump myself).

![MenuUI](https://github.com/emoose/OutRun2006Tweaks/assets/4377861/37dde208-0e4c-466c-aac5-319493fea23e)
![GameplayUI](https://github.com/emoose/OutRun2006Tweaks/assets/4377861/fb827a98-83d6-44d9-bc05-8eda158fc4b6)

I figured I'd check the dumped texture of the car radio in C2C PC to see if the stretch is occuring at the texture level. It seems to mostly match the original 4:3 texture of the Arcade version, so the stretch might be forced by the game everywhere

![MenuUI1 C2C PC](https://github.com/emoose/OutRun2006Tweaks/assets/4377861/485574ce-7664-4c39-8728-d1c53de1e711)

Though I think menu UI is inconsequential compared to the UI during the actual racing. Sorry for wasting time if it's not feasible

EDIT: for the sake of being exhaustive, I loaded up Outrun online arcade on PS3, and it displays the UI without stretching too despite being based on C2C by the same developers

![RPCS3 OROA](https://github.com/emoose/OutRun2006Tweaks/assets/4377861/b50aa28a-3785-4cab-9a8e-40a95612685e)

**Comment by DonelBueno** [comment] 2024-06-24 16:34
Duplicate of #2.

**Comment by emoose** [comment] 2024-07-11 00:11
Left this open since it was more menu related, but since that's also fixed in #2 now I guess we can close this, thanks for the suggestion with online arcade btw, was a big help with the spacing fixes.

**Closed by emoose** 2024-07-11 00:11 UTC

**Comment by lance8765** [comment] 2024-07-11 17:31
> Left this open since it was more menu related, but since that's also fixed in #2 now I guess we can close this, thanks for the suggestion with online arcade btw, was a big help with the spacing fixes.

Can you please close this too? https://github.com/emoose/OutRun2006Tweaks/issues/28

Thank you.
